return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    opts = {
        auto_install = true,
        highlight = {
            enable = true,
            use_languagetree = true,
            additional_vim_regex_highlighting = false,
        },
        ensure_installed = {
            "c",
            "cpp",
            "cmake",
            "ini",
            "vim",
            "lua",
            "vimdoc",
            "kotlin",
            "python",
            "angular",
            "javascript",
            "typescript",
            "yaml",
            "json",
            "bash",
            "html",
            "css",
            "markdown",
            "markdown_inline",
            "tsx",
        },
    },
}
